fileVersion: 1
id: "25"
mappingDefinitions:
  OUTPUT:
    database: SUVI_SYSADMIN
    schema: DEV
  SOURCE:
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
name: New Environment Test
type: Environment
