fileVersion: 1
id: "25"
mappingDefinitions:
  OUTPUT:
    database: SUVI_SYSADMIN
    schema: DEV
  OUTPUTBRANDNEW:
    database: ""
    schema: ""
  SDDF-GSFDGDFGDFGDFH-FDGH-DSGF-DFBDSFBGDGSGHDFBDG-BGFBNFGSGCREGCERGC-ERCGE54VE-G5VEHGVC56VTHR-V6RVH5VTG54EYCG54C-GCHE5CH54E5CEH5E-CEH5E5CEHTG5ECHC-54HCECHE5CRHC4W5C-CE5CH45EC5CHQ5CQ5C4-QCHQ45H45QCH45Q5-TTTTTTTTTTT-TTTTTTTT-GGGGGG:
    database: ""
    schema: ""
  SOURCE:
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
name: New Environment Test
type: Environment
